version: "3.1"
services:
  scheduler:
    volumes:
      - ./output:/usr/local/airflow/output
      - ./database/my_sqlite.db:/usr/local/airflow/database/my_sqlite.db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: vii
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers_db
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./sql_statements:/var/lib/postgresql/sql_statements
    ports:
      - "5434:5432"